import { generateOpenAiImageObjectQuery } from '@/platforms/openai';
import {
  AiAutoGeneratedField,
  getAiImageQuerySchema,
  getAiTextFieldsToGenerate,
} from '.';
import { AI_TEXT_AUTO_GENERATED_FIELDS } from '@/app/config';
import { PhotoFormData } from '../form';

export const generateAiImageQueries = async ({
  imageBase64,
  textFieldsToGenerate = [],
  existingTitle,
  isBatch,
}: {
  imageBase64?: string
  textFieldsToGenerate: AiAutoGeneratedField[]
  existingTitle?: string
  isBatch?: boolean
}): Promise<{
  title?: string
  caption?: string
  semantic?: string
  error?: string
}> => {
  if (imageBase64) {
    try {
      const { query, schema } = getAiImageQuerySchema(
        textFieldsToGenerate,
        existingTitle,
      );
      return generateOpenAiImageObjectQuery(
        imageBase64,
        query,
        schema,
        isBatch,
      );
    } catch (e: any) {
      return {
        error: e.message,
      };
    }
  } else {
    return {
      error: 'No image provided',
    };
  }
};

export const addAiTextToFormData = async ({
  formData = {},
  imageBase64,
  existingTitle,
}: {
  formData?: Partial<PhotoFormData>
  imageBase64?: string
  existingTitle?: string
}): Promise<Partial<PhotoFormData>> => {
  const {
    title: aiTitle,
    caption: aiCaption,
    semantic,
  } = await generateAiImageQueries({
    imageBase64,
    textFieldsToGenerate: getAiTextFieldsToGenerate(
      AI_TEXT_AUTO_GENERATED_FIELDS,
      Boolean(existingTitle || formData?.title),
      Boolean(formData?.caption),
    ),
    existingTitle: existingTitle || formData?.title,
  });

  return {
    ...formData,
    title: formData?.title || aiTitle,
    caption: formData?.caption || aiCaption,
    semanticDescription: semantic,
  };
};
